[package]
name = "mystery_box"
version = "0.1.0"
anchor_version = "1.0.1"

[programs.localnet]
mystery_box = "4GwYrYmaEQqGH3B69kiaxHsjJS5XbK5a3m1ttt5cajqJ"

[programs.devnet]
mystery_box = "4GwYrYmaEQqGH3B69kiaxHsjJS5XbK5a3m1ttt5cajqJ"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[hooks]
pre-build = "cargo build --lib --profile release --target sbf-solana-solana"