[package]
name = "mystery_box"
version = "0.1.0"
anchor_version = "1.0.1"

[programs.localnet]
mystery_box = "5GA4F3dUw4uZc63UFRQxcyqZBA1TMvDG9p9XzAVCojwD"

[programs.devnet]
[programs.mainnet]
mystery_box = "HnysT79HmiJWWtE8W2LWbhBeXk27RxoohbJ4cQyw8AKr"

[provider]
cluster = "mainnet"
wallet = "../authority.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[hooks]
pre-build = "cargo build-sbf"