[package]
name = "mystery_box"
version = "0.1.0"
anchor_version = "1.0.1"

[programs.localnet]
mystery_box = "45krUFivAX6f3zkH5CkWRkQWc8FDLjxLiHZyGVfBvzYW"

[programs.devnet]
mystery_box = "45krUFivAX6f3zkH5CkWRkQWc8FDLjxLiHZyGVfBvzYW"

[provider]
cluster = "localnet"
wallet = "../authority.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[hooks]
pre-build = "cargo build --lib --profile release --target sbf-solana-solana"