use anchor_lang::prelude::*;

#[error_code]
pub enum MysteryBoxError {
    Unauthorized,
    PlatformPaused,
    ProjectInactive,
    BoxNotActive,
    BoxSoldOut,
    BoxAlreadyEnded,
    InsufficientPayment,
    InvalidPrizeType,
    InvalidMint,
    DepositMismatch,
    BoxNotEnded,
    NoPrizeClaimsRemaining,
    BoxHasPendingReceipts,
    InvalidSlug,
    InsufficientFunds,
    MathOverflow,
    TokenAccountNotEmpty,
    InvalidWinPercentage,
    AlreadyPendingReveal,
    NoPendingReveal,
    SameSlotReveal,
    SlotHashNotFound,
    RequestExpired,
    NoPurchasedBoxes,
    ProjectHasActiveBoxes,
    InvalidPrizeIndex,
    PendingPrizesExist,
}
